
invisible(
  capture.output(
    suppressWarnings(
      suppressMessages({
        suppressPackageStartupMessages({
          library(ggplot2)
          library(tidyverse)
          library(patchwork)
          library(gtsummary)
          library(here)
          library(kableExtra)
          library(ggfortify)
          library(AICcmodavg)
          library(HSAUR3)
          library(vegan)
          library(car)
          library(broom)
          library(knitr)
          library(plotly)
          library(lme4)
          #library(lmerTest)
        })
      })
    )
  )
)
