::: {.callout-warning}
**Under construction**: This 2026 version of this book is currently being prepared. Some chapters are not yet available, and some content may change before the course starts in February 2026.
:::


# Preface {.unnumbered}


This book contains the content of the course BIO144 Data Analysis in Biology at the University of Zurich. It is intended to be used as a companion to the lectures and practical exercises of the course. All of the required content of the course (i.e., what could be in the final exam) is included in this book. Additional content is included for those who want to learn more.

Beware that Owen sometimes makes updates to the book during the semester, so if you have downloaded a copy or taken screenshots, your copy may not exactly match the most current version. However, all of the required content will be the same, and any changes will be correcting typos or improving explanations. If content does change in a way that would change the answer to a question in the final exam, Owen will announce this in the lectures and on OLAT.

## How to get a copy of this book {.unnumbered}

If you'd like a copy of this book for yourself, there are a few ways. But beware: if you take a local copy then it will not be updated when Owen makes changes to the online version!

* You can download a PDF version of the entire book: <a href="BIO144-Course-Book--version-2026-.pdf" target="_blank">
  📄 Download PDF
</a>

* You can download a complete local copy of the HTML version of the BIO144 course book from here:  
[https://github.com/opetchey/BIO144_Course_Book/tree/main](https://github.com/opetchey/BIO144_Course_Book/tree/main). The html files for the book are in the `_book` folder, and this is the only folder you need for your offline html copy of the book. You can open the `index.html` file in your web browser to read the book offline.

* You can get all of the source code for the book from the [GitHub repository](https://github.com/opetchey/BIO144_Course_Book). However, you may find it a little complicated to do anything useful with it!

## Datasets are not real

The datasets used in this book are not real datasets. They were created to illustrate the methods taught in the course. Any resemblance to real data is purely coincidental. Please do not use these datasets for any purpose other than learning the methods taught in this course. The patterns in the data may not reflect real-world patterns, and should not be used to draw any conclusions about real-world phenomena.

## Getting the datasets

The datasets used in this book are available for download as a zip file here: [course_book_datasets.zip](course_book_datasets.zip). You can download this file and unzip it to get all of the datasets used in the book. The datasets are in CSV format, which can be opened in R or other statistical software.

## Packages used in this book

This book uses a number of R add-on packages for data analysis and visualization. You will need to install these packages in order to run the code in the book. The required packages are listed in the `_common.r` file in the GitHub repository for the book. Here is a link to that file: [_common.R](https://raw.githubusercontent.com/opetchey/BIO144_Course_Book/refs/heads/main/_common.R). You can copy and paste the list of packages from that file into your R console to install them.

## If you think you found a mistake in this book {.unnumbered}

If you think you have found a mistake in the book, please say. A really nice way is to submit an issue on the GitHub repository for the book: [Issues page of the GitHub repository](https://github.com/opetchey/BIO144_Course_Book/issues). You will need a GitHub account to do this, but they are free and easy to set up. Otherwise tell Owen in person sometime, or in the OLAT Forum, or by email.

When reporting a mistake, please be as specific as possible about where the mistake is. A screenshot works well. Or give the chapter and section number, and copy a chunk of text, as well as a description of the issue problem of course!

## How this book was made

The book was written using a type of RMarkdown. It allows a script with a mix of normal text and R code to produce chapters and a book that has a mixture of text, R code, and R output. Rmarkdown is very useful for making reports, books, presentations, and even websites.

This book is a Quarto book. To learn more about Quarto books visit <https://quarto.org/docs/books>.


## Acknowledgements {.unnumbered}

The content was based on lectures originally written by [Dr Stefanie Muff](https://www.ntnu.edu/employees/stefanie.muff).

The content of the book was written with the assistance of [Github Copilot](https://copilot.github.com/), an AI tool that helps write code and text.
