# Data wrangling and visualisation (L2) {.unnumbered}

```{r}
#| echo: false
source("_common.R")
```


::: {.callout-note}
This chapter in under development.
:::

## Data wrangling

Functions in the `dplyr` package are used to manipulate data frames:

* `select()`: select columns by position, or by name, or by other methods
* `slice()`: select rows by position
* `filter()`: select rows that meet a logical condition
* `arrange()`: reorder rows
* `mutate()`: add new variables

The `dplyr` package also provides functions to group data frames and to summarize data:

* `group_by()`: add to a data frame a grouping structure
* `summarize()`: summarize data, respecting any grouping structure specified by `group_by()`

The pipe operator `|>` is used to chain together multiple operations on a data frame. 

::: {.callout-note}
Note that you will often see another pipe operator `%>%` used in examples. The pipe operator `|>` is a newer version of `%>%` that is more efficient and easier to use. The pipe operator `|>` is available in R version 4.1.0 and later.
:::

## Visualisation

We will use the `ggplot2` package to create visualisations. The `ggplot2` package is based on the grammar of graphics, which provides a consistent way to create visualisations.

Types of visualisation:

* Scatter plots
* Histograms
* Box and whisker plots

Beautify visualisations with themes and labels.
