<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Interactions (L7) – BIO144 Course Book (version 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./8.1-GLM1-count-data.html" rel="next">
<link href="./6.1-multiple-regression.html" rel="prev">
<link href="./cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./7.1-interactions.html">Interactions (L7)</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BIO144 Course Book (version 2026)</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/opetchey/BIO144_Course_Book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1.1-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction (L1)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2.1-R-and-RStudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R and RStudio (L2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3.1-regression-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression Part 1 (L3)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4.1-regression-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression Part 2 (L4)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5.1-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis of variance (L5)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6.1-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiple regression (L6)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7.1-interactions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Interactions (L7)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8.1-GLM1-count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Count data (L8)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9.1-GLM2-binary-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Binomial data (L9)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10.1-ordination.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ordination (L10)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11.1-mixed-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mixed models (L11-1)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11.2-what-next.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What next (L11-2)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12.1-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Review (L12)</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#thought-for-the-week" id="toc-thought-for-the-week" class="nav-link active" data-scroll-target="#thought-for-the-week">Thought for the week:</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#parallel-and-non-parallel-effects" id="toc-parallel-and-non-parallel-effects" class="nav-link" data-scroll-target="#parallel-and-non-parallel-effects">Parallel and non-parallel effects</a></li>
  <li><a href="#two-cats" id="toc-two-cats" class="nav-link" data-scroll-target="#two-cats">Two cats</a></li>
  <li><a href="#two-continuous" id="toc-two-continuous" class="nav-link" data-scroll-target="#two-continuous">Two continuous</a></li>
  <li><a href="#other-perspectives" id="toc-other-perspectives" class="nav-link" data-scroll-target="#other-perspectives">Other perspectives</a>
  <ul class="collapse">
  <li><a href="#interactions-and-additivity-of-effects" id="toc-interactions-and-additivity-of-effects" class="nav-link" data-scroll-target="#interactions-and-additivity-of-effects">Interactions and additivity of effects</a></li>
  <li><a href="#drug-interactions" id="toc-drug-interactions" class="nav-link" data-scroll-target="#drug-interactions">Drug interactions</a></li>
  </ul></li>
  <li><a href="#the-maths-bit" id="toc-the-maths-bit" class="nav-link" data-scroll-target="#the-maths-bit">The maths bit</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis testing</a></li>
  <li><a href="#doing-it-in-r" id="toc-doing-it-in-r" class="nav-link" data-scroll-target="#doing-it-in-r">Doing it in R</a></li>
  <li><a href="#reporting-our-findings" id="toc-reporting-our-findings" class="nav-link" data-scroll-target="#reporting-our-findings">Reporting our findings</a></li>
  <li><a href="#multiple-regression-vs.-many-single-regressions" id="toc-multiple-regression-vs.-many-single-regressions" class="nav-link" data-scroll-target="#multiple-regression-vs.-many-single-regressions">Multiple regression vs.&nbsp;many single regressions</a></li>
  <li><a href="#ancova" id="toc-ancova" class="nav-link" data-scroll-target="#ancova">ANCOVA</a></li>
  <li><a href="#two-way-anova" id="toc-two-way-anova" class="nav-link" data-scroll-target="#two-way-anova">Two-way ANOVA</a>
  <ul class="collapse">
  <li><a href="#more-than-two-levels" id="toc-more-than-two-levels" class="nav-link" data-scroll-target="#more-than-two-levels">More than two levels</a></li>
  </ul></li>
  <li><a href="#multiple-regression-with-interaction-term" id="toc-multiple-regression-with-interaction-term" class="nav-link" data-scroll-target="#multiple-regression-with-interaction-term">Multiple regression with interaction term</a></li>
  <li><a href="#intepreting-main-effects-and-interaction-effects" id="toc-intepreting-main-effects-and-interaction-effects" class="nav-link" data-scroll-target="#intepreting-main-effects-and-interaction-effects">Intepreting main effects and interaction effects</a></li>
  <li><a href="#more-than-two-explanatory-variables" id="toc-more-than-two-explanatory-variables" class="nav-link" data-scroll-target="#more-than-two-explanatory-variables">More than two explanatory variables</a></li>
  <li><a href="#review" id="toc-review" class="nav-link" data-scroll-target="#review">Review</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading">Further reading</a></li>
  <li><a href="#extras" id="toc-extras" class="nav-link" data-scroll-target="#extras">Extras</a>
  <ul class="collapse">
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of freedom</a></li>
  <li><a href="#d-scatter-plot" id="toc-d-scatter-plot" class="nav-link" data-scroll-target="#d-scatter-plot">3d scatter plot</a></li>
  <li><a href="#types-of-sums-of-squares" id="toc-types-of-sums-of-squares" class="nav-link" data-scroll-target="#types-of-sums-of-squares">Types of sums of squares</a></li>
  <li><a href="#box-and-whisker-plot-for-two-cats" id="toc-box-and-whisker-plot-for-two-cats" class="nav-link" data-scroll-target="#box-and-whisker-plot-for-two-cats">Box and whisker plot for two cats</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/opetchey/BIO144_Course_Book/edit/main/7.1-interactions.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/opetchey/BIO144_Course_Book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Interactions (L7)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="thought-for-the-week" class="level2">
<h2 class="anchored" data-anchor-id="thought-for-the-week">Thought for the week:</h2>
<p>“<em>You should arrive at answers on your own, and not rely upon what you get from someone else. Answers from others are nothing more than stopgap measures, they’re of no value.</em>”</p>
<ul>
<li>Ichiro Kishimi &amp; Fumitake Koga, The Courage to Be Disliked</li>
</ul>
<p>They instead encourage answers gained from curiosity, observation, and dialogue. Answers you develop for yourself are more likely to stick with you, and to be meaningful.</p>
<p>When we mentor, ask questions that encourage others to think for themselves, rather than simply giving answers. This is hard, but worthwhile.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>In the previous chapters we have looked at models with a special type of simplicity: the effect of each explanatory variable on the response variable is independent of the other explanatory variables. This is special because it means that we can understand the effect of each explanatory variable on the response variable separately, without considering the other explanatory variables. Nevertheless, this is often not the case in real life. The effect of one explanatory variable on the response variable may depend on the value of another explanatory variable. This is called an interaction effect, or simply an interaction.</p>
<p>Interactions are some of the most interesting phenomena in science, including biology. We are not talking about interactions between species, like predation, though these are also very interesting. We are talking about effects of one thing, like diet, depending on another thing, like exercise. Let’s break that down a bit…</p>
<p>Imagine we make a study of the effect of exercise (minutes per week) on blood pressure for people with a meat heavy diet.</p>
<p>Read in the dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>bp_meatheavy <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/bp_meatheavy.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the first few rows of the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bp_meatheavy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         bp mins_per_week       diet
1  94.12854      53.10173 meat heavy
2  90.99957      74.42478 meat heavy
3  73.83541     114.57067 meat heavy
4  77.05434     181.64156 meat heavy
5 100.14578      40.33639 meat heavy
6  95.61900     179.67794 meat heavy</code></pre>
</div>
</div>
<p>And here is a graph of the relationship between blood pressure and minutes of exercise for people with a meat heavy diet:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>We see that exercise seems to lower blood pressure. But what if we look at the effect of exercise on blood pressure for people with a vegetarian diet? The relationship might look something like this:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         bp mins_per_week       diet
1  77.56704     122.92899 vegetarian
2  84.30684     111.43191 vegetarian
3  75.23323      65.75546 vegetarian
4  85.67402      90.62629 vegetarian
5  77.45327     100.08819 vegetarian
6 102.31114      36.17327 vegetarian</code></pre>
</div>
</div>
<p>Read in the dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>bp_vegetarian <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/bp_vegetarian.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here is a graph of the relationship between blood pressure and minutes of exercise for people with a vegetarian diet:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>We see that exercise seems to lower blood pressure for vegetarians too, but the effect seems to be weaker.</p>
<p>To summarise this finding, we can say that the effect of exercise on blood pressure is stronger for people with a meat heavy diet than for people with a vegetarian diet. This means that the effect of exercise on blood pressure depends on diet.</p>
<p>This is very clear when we look at the both diets in the same graph:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>(The dataset with both combined is in the file <code>bp_1cont1cat.csv</code>.)</p>
<!---
**Think-Pair-Share** (#tps-general-diet) Can we say anything general about the effect of diet on blood pressure?

No, we can't. We cannot, for example, state that a vegetarian diet lowers blood pressure. We can say, however, that a vegetarian diet lowers blood pressure of people that do little exercise.
--->
<!---
**Think-Pair-Share** (#tps-general-exercise) Can we say anything general about the effect of exercise on blood pressure?

Well, we can say that exercise lowers blood pressure, but we have to be careful. We have to say that exercise lowers blood pressure of people with a meat heavy diet more than it lowers blood pressure of people with a vegetarian diet.
--->
<p>I think it is clear that the interaction was easier to see when we plotted all the data in one graph… it is much easier to visually compare the slopes of the two regression lines when they are on the same graph.</p>
<p>As we will see later in this chapter, the same holds true for statistical tests of interactions: it is much easier to make a statistical test of the interaction when we make a single model with <em>an interaction term</em>.</p>
<p>It is harder and is not recommended to make a separate regression for each level of the second variable (diet) and then compare the slopes of the regression lines (it is possible, just not at all efficient).</p>
</section>
<section id="parallel-and-non-parallel-effects" class="level2">
<h2 class="anchored" data-anchor-id="parallel-and-non-parallel-effects">Parallel and non-parallel effects</h2>
<p>In the example above, the effect of exercise on blood pressure was stronger for people with a meat heavy diet than for people with a vegetarian diet. That is, the slope of the regression line was steeper for the meat heavy diet than for the vegetarian diet. Put another way, the regression lines are not parallel.</p>
<p><strong>Parallel = no interaction</strong>: Parallel regression lines are evidence of no interaction. This means that the effect of one variable (exercise) is the same for all levels of another variable (diet).</p>
<p><strong>Non-parallel = interaction</strong>: When the regression lines are not parallel, there is evidence of an interaction. This means that the effect of one variable (exercise) depends on the level of another variable (diet).</p>
<p>That was an example of an interaction between a continuous explanatory variable (exercise) and a categorical explanatory variable (diet). Interactions can also occur between two categorical explanatory variables, or between two continuous explanatory variables. Let us look at some more examples.</p>
<!---
**Think–Pair–Share** (#a_when_lines_cross) What does it mean biologically when lines cross in an interaction plot? What does it mean when they are parallel?
--->
</section>
<section id="two-cats" class="level2">
<h2 class="anchored" data-anchor-id="two-cats">Two cats</h2>
<p>Two categorical explanatory variables: diet (meat heavy or vegetarian) and exercise (low or high), and one continuous response variable (blood pressure).</p>
<p>Read in the dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>bp_2cat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/bp_2cat.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the first few rows of the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bp_2cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        diet exercise reps        bp
1 meat heavy     high    1  83.73546
2 meat heavy      low    1 115.11781
3 vegetarian     high    1  74.18977
4 vegetarian      low    1 108.58680
5 meat heavy     high    2  91.83643
6 meat heavy      low    2 103.89843</code></pre>
</div>
</div>
<p>And here is the data in a graph, where we show the individual data points as well as the group means connected by lines. The lines connecting the means are only to help visualize whether there is an interaction or not. If we see non-parallel lines connecting the means, we have evidence of an interaction.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Indeed, the lines connecting the means are not parallel, which is evidence of an interaction between diet and exercise on blood pressure.</p>
<!---
**Think-Pair-Share** (#tps-express-int) Express the nature of the interaction in words.
--->
</section>
<section id="two-continuous" class="level2">
<h2 class="anchored" data-anchor-id="two-continuous">Two continuous</h2>
<p>Two continuous explanatory variables (age and exercise minutes) and one continuous response variable (blood pressure).</p>
<p>Read in the dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bp_2cont <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/bp_2cont.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here is the first few rows of the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bp_2cont)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         bp      age mins_per_week
1  61.58319 35.93052     130.94479
2  83.86716 42.32743      70.63945
3  93.01438 54.37120      54.05203
4  82.14413 74.49247     198.53681
5  60.13102 32.10092     126.69865
6 102.00306 73.90338      42.64163</code></pre>
</div>
</div>
<p>Now we have a little challenge, namely that we have two continuous explanatory variables. This means that we need to use three dimensions to visualize the data. Here is a standard 2D scatter plot of blood pressure against minutes of exercise, though with age represented by color grading from young (dark blue) to old (yellow):</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>And we can make the complementary plot of blood pressure against age, with minutes of exercise represented by color grading from low (green) to high (orange):</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="528"></p>
</figure>
</div>
</div>
</div>
<p>What do we see? If we look at a set of points of the similar colour (i.e., similar number of minutes of exercised), we can see that the slope of the relationship between blood pressure and age depends on exercise. The slope is steeper for people that exercise more.</p>
<!---
**Think-Pair-Share** (#tps-small-older) Another thing we could say is that the effect of exercise is smaller for older people. How is this shown in the graph?
--->
<p>Yet another way to visualise this interaction is to create categorical versions of age and minutes of exercise, and then plot the data with these categorical variables:</p>
<p>Here is the first few rows of the modified data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bp_2cont)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         bp      age mins_per_week age_class mins_per_week_class
1  61.58319 35.93052     130.94479     30-40             120-140
2  83.86716 42.32743      70.63945     40-50               60-80
3  93.01438 54.37120      54.05203     50-60               40-60
4  82.14413 74.49247     198.53681     70-80             180-200
5  60.13102 32.10092     126.69865     30-40             120-140
6 102.00306 73.90338      42.64163     70-80               40-60</code></pre>
</div>
</div>
<p>And here is the plot of blood pressure against minutes of exercise, with age class represented by colour. Regression lines have been added, to help visualize any interaction:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>It is as we saw in the previous version of the graph. The slope of the relationship between blood pressure and minutes of exercise depends on age. The slope is shallower for older people.</p>
<p>In the complementary graph of blood pressure against age, with minutes of exercise represented by colour, we see the same interaction:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>There is only one interaction</strong> We made two graphs of the same data, one with age as a categorical variable and one with minutes of exercise as a categorical variable. In both graphs we see an interaction. This is not us seeing two separate interactions, however. There is only one interaction here, namely that the effect of age on blood pressure depends on minutes of exercise, and equivalently, that the effect of minutes of exercise on blood pressure depends on age. The two graphs just look at the same interaction from different perspectives.</p>
</div>
</div>
</section>
<section id="other-perspectives" class="level2">
<h2 class="anchored" data-anchor-id="other-perspectives">Other perspectives</h2>
<section id="interactions-and-additivity-of-effects" class="level3">
<h3 class="anchored" data-anchor-id="interactions-and-additivity-of-effects">Interactions and additivity of effects</h3>
<p>Another way of thinking about interactions is from the perspective of additivity or non-additivity of effects. Imagine we made two separate studies, one of the effect of diet on blood pressure, and one of the effect of exercise on blood pressure. In the first study we only varied diet, and in the second study we only varied exercise. In the first study we found an effect size of diet on blood pressure of say 10 mmHg (e.g., difference between meat heavy and vegetarian). And in the second study we found an effect size of exercise on blood pressure of 15 mmHg (e.g., difference between low and high exercise).</p>
<!---
**Think-Pair-Share** (#tps-adding-effects) If the effects of diet and exercise were additive, what would we expect the effect size to be if we estimated the effect of diet and exercise on blood pressure in the same study?
--->
<!---
**Think-Pair-Share** (#tps-comb-non-add) What would we expect the effect size of combined diet and exercise to be if the effects were non-additive? (Hint: this is a bit of a trick question.)
--->
<p>If the effects are non-additive, we would expect the effect size to be different from additive. For example, if we found the combined effect of diet and exercise on blood pressure to be 40, we would say that the effects are non-additive. Their combined effect is more than the sum of their individual effects. This example is of a synergistic interaction because the combined effect (40) is greater than the sum of the individual effects (25).</p>
</section>
<section id="drug-interactions" class="level3">
<h3 class="anchored" data-anchor-id="drug-interactions">Drug interactions</h3>
<p>When a doctor is considering giving us a particular medication, we are asked if we are taking any other medications. This is because the effects of drugs can interact. For example, if we take two drugs that both lower blood pressure and they interfere with each other, the combined effect might be less than the sum of their individual effects. This is an antagonistic interaction. It could be worse than that though, the interaction might actually be harmful, which is why doctors are so careful about drug interactions.</p>
<!---
**Think-Pair-Share** (#tps-other-int-examples) Can you think of any other examples of interactions in biology or medicine?
--->
</section>
</section>
<section id="the-maths-bit" class="level2">
<h2 class="anchored" data-anchor-id="the-maths-bit">The maths bit</h2>
<p>Let us return to the example of the effects of number of minutes of exercise and diet on blood pressure:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="528"></p>
</figure>
</div>
</div>
</div>
<p>We have one continuous explanatory variable (minutes of exercise) and one binary explanatory variable (diet) and one continuous response variable (blood pressure).</p>
<!---
**Think-Pair-Share** (#tps-without-interaction) What would a linear model without an interaction term be?
--->
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_{i}^{(1)} + \beta_2 x_{i}^{(2)} + \epsilon_i\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(y_i\)</span> is the blood pressure of the <span class="math inline">\(i\)</span>th participant</li>
<li>$x_i^{(1)} is the number of minutes of exercise of the <span class="math inline">\(i\)</span>th participant</li>
<li><span class="math inline">\(x_i^{(2)}\)</span> is the diet of the <span class="math inline">\(i\)</span>th participant</li>
<li><span class="math inline">\(\beta_0\)</span> is the intercept</li>
<li><span class="math inline">\(\beta_1\)</span> is the effect of exercise on blood pressure</li>
<li><span class="math inline">\(\beta_2\)</span> is the effect of diet on blood pressure</li>
<li><span class="math inline">\(\epsilon_i\)</span> is the error term for the <span class="math inline">\(i\)</span>th participant.</li>
</ul>
<p>This model is a multiple regression model in which one of the explanatory variables is binary.</p>
<!---
**Think-Pair-Share** (#tps-with-interaction) What might the model look like if we wanted to include an interaction between diet and exercise?
--->
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_{i}^{(1)} + \beta_2 x_{i}^{(2)} + \beta_3 (x_{i}^{(1)} x_{i}^{(2)}) + \epsilon_i\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(x_{i}^{(1)}x_{i}^{(2)}\)</span> is the product of the number of minutes of exercise and the diet of the <span class="math inline">\(i\)</span>th participant.</li>
<li><span class="math inline">\(\beta_3\)</span> is the coefficient of the interaction term between diet and exercise.</li>
</ul>
<p>We could also write this model as:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_{i}^{(1)} + \beta_2 x_{i}^{(2)} + \beta_3 x_{i}^{(3)} + \epsilon_i\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(x_{i}^{(3)} = x_{i}^{(1)} x_{i}^{(2)}\)</span></li>
</ul>
<p>This is again a multiple regression model, but now with three explanatory variables.</p>
<!---
**Think-Pair-Share** (#tps-sketch-interaction) Make sketches of the possible relationships between diet, exercise and blood pressure. Make a sketch compatible with $\beta_3 = 0$. Make a sketch compatible with $\beta_3 \neq 0$.
--->
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis testing</h2>
<p>If we want to test whether the effect of minutes of exercise on blood pressure is different for people with different diets, we need a null hypothesis to test.</p>
<!---
**Think-Pair-Share** (#tps-interaction-null) What is the null hypothesis in this case, verbally, and in terms of the coefficients of the model?
--->
<p>The null hypothesis is that the effect of minutes of exercise on blood pressure is the same for people with different diets. This is a null hypothesis of no interaction between diet and exercise. In terms of the coefficients of the model, the null hypothesis is that <span class="math inline">\(\beta_3 = 0\)</span>.</p>
<p>If we reject the null hypothesis, we conclude that the effect of minutes of exercise on blood pressure is different for people with different diets. This is a non-additive effect.</p>
</section>
<section id="doing-it-in-r" class="level2">
<h2 class="anchored" data-anchor-id="doing-it-in-r">Doing it in R</h2>
<p>Let us fit the model with the interaction term in R. There are two methods to do this and they are equivalent:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bp <span class="sc">~</span> mins_per_week <span class="sc">+</span> diet <span class="sc">+</span> mins_per_week<span class="sc">:</span>diet, <span class="at">data=</span>bp_1cont1cat)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bp <span class="sc">~</span> mins_per_week <span class="sc">*</span> diet, <span class="at">data=</span>bp_1cont1cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The second is a shorthand for the first. The <code>*</code> operator includes the main effects (main effects are terms in the model that don’t include interactions) and the interaction term. The <code>:</code> operator includes only the interaction term.</p>
<p>Of course, we check the model assumptions before we interpret the results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod2, <span class="at">add.smooth=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>All of the plots look good. Now we can do hypothesis testing of the interaction term using an F-test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bp
                   Df Sum Sq Mean Sq F value    Pr(&gt;F)    
mins_per_week       1 1133.6 1133.55 13.4800 0.0003964 ***
diet                1 1560.8 1560.75 18.5601 3.979e-05 ***
mins_per_week:diet  1  340.4  340.36  4.0475 0.0470408 *  
Residuals          96 8072.8   84.09                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>In the ANOVA table we see four rows. The first row is for the main effect of minutes of exercise, the second row is for the main effect of diet, the third row is for the interaction effect between diet and minutes of exercise, and the fourth row is for the residuals. As always, an interaction term in the R output is shown with a colon <code>:</code> between the two variables (here it looks like <code>mins_per_week:diet</code>).</p>
<p>In this example, the F-statistic for the interaction term is quite large (4.05), and the p-value is very small (0.047). This means that we reject the null hypothesis that there is no interaction between diet and minutes of exercise on blood pressure. We conclude that the effect of minutes of exercise on blood pressure is different for people with different diets.</p>
<p>If we like (and we don’t have to), we can look at the coefficients of the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                 Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)                  100.62716134 2.87228930 35.033783 1.714199e-56
mins_per_week                 -0.09661054 0.02406014 -4.015376 1.177969e-04
dietvegetarian               -15.27591304 4.09882726 -3.726898 3.275630e-04
mins_per_week:dietvegetarian   0.06907583 0.03433487  2.011828 4.704076e-02</code></pre>
</div>
</div>
<p>As expected, there are four coefficients.</p>
<p>The first is <code>(Intercept)</code>, which is the expected blood pressure for a person who does 0 minutes of exercise and is on diet “meat heavy”.</p>
<p>The second is <code>mins_per_week</code>, which is the effect (slope) of minutes of exercise on blood pressure for a person on diet “meat heavy”.</p>
<p>The third is <code>dietvegetarian</code>, which is the effect of being on a vegetarian diet on blood pressure for a person who does 0 minutes of exercise. This can be thought of as the change in the intercept for a person on a vegetarian diet compared to a person on a “meat heavy” diet.</p>
<p>The fourth is the interaction term <code>mins_per_week:dietvegetarian</code>, which is the difference in the effect (slope) of minutes of exercise on blood pressure for a person on a vegetarian diet compared to a person on a “meat heavy” diet.</p>
<!---
**Think-Pair-Share** (#tps-two-equations) Write two equations, one for each of the two diets. They would look something like this: $y_i = 0.1 - 0.1 x_{i}^{(1)}$, but will have other numbers.
--->
</section>
<section id="reporting-our-findings" class="level2">
<h2 class="anchored" data-anchor-id="reporting-our-findings">Reporting our findings</h2>
<p>Of course a nice graph is always helpful. We already have quite a nice one:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="528"></p>
</figure>
</div>
</div>
</div>
<p>We also might want some tables summarizing the model results. Here is a table of the coefficients:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">100.6271613</td>
<td style="text-align: right;">2.8722893</td>
<td style="text-align: right;">35.033783</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">mins_per_week</td>
<td style="text-align: right;">-0.0966105</td>
<td style="text-align: right;">0.0240601</td>
<td style="text-align: right;">-4.015377</td>
<td style="text-align: right;">0.0001178</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dietvegetarian</td>
<td style="text-align: right;">-15.2759130</td>
<td style="text-align: right;">4.0988273</td>
<td style="text-align: right;">-3.726898</td>
<td style="text-align: right;">0.0003276</td>
</tr>
<tr class="even">
<td style="text-align: left;">mins_per_week:dietvegetarian</td>
<td style="text-align: right;">0.0690758</td>
<td style="text-align: right;">0.0343349</td>
<td style="text-align: right;">2.011828</td>
<td style="text-align: right;">0.0470408</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We could also report the <span class="math inline">\(R^2\)</span> of the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2732093</code></pre>
</div>
</div>
<p>And also a table of the variances of the terms in the model:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sum Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean Sq</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mins_per_week</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1133.554</td>
<td style="text-align: right;">1133.55446</td>
<td style="text-align: right;">13.47998</td>
<td style="text-align: right;">0.0003964</td>
</tr>
<tr class="even">
<td style="text-align: left;">diet</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1560.753</td>
<td style="text-align: right;">1560.75255</td>
<td style="text-align: right;">18.56012</td>
<td style="text-align: right;">0.0000398</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mins_per_week:diet</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">340.357</td>
<td style="text-align: right;">340.35702</td>
<td style="text-align: right;">4.04745</td>
<td style="text-align: right;">0.0470408</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">8072.804</td>
<td style="text-align: right;">84.09171</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We also might use a sentence like this to report the results: “The effect of minutes of exercise is generally negative, but the effect is stronger for people on a meat heavy diet than for people on a vegetarian diet (<span class="math inline">\(F\)</span>-statistics of interaction term = 4.05, degrees of freedom = 1, degrees of freedom residuals = 96, <span class="math inline">\(p\)</span>-value = 0.047).”</p>
<!---
**Think–Pair–Share (#a_interaction_vs_main_effect)** How does an interaction change the meaning of a "main effect"? Can a main effect be misleading when an interaction is present?
--->
</section>
<section id="multiple-regression-vs.-many-single-regressions" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-vs.-many-single-regressions">Multiple regression vs.&nbsp;many single regressions</h2>
<p>Question: Why not just fit a separate simple regression model and then test whether the slopes are the same (i.e., if they are parallel)? That is, why not fit the two models:</p>
<p><span class="math display">\[y_i = \beta_{0,veg} + \beta_{1,veg} x_i^{(1)} + \epsilon_i\]</span></p>
<p><span class="math display">\[y_i = \beta_{0,meat} + \beta_{1,meat} x_i^{(2)} + \epsilon_i\]</span></p>
<p>and compare the estimate of <span class="math inline">\(\beta_{1,veg}\)</span> to the estimate of <span class="math inline">\(\beta_{1,meat}\)</span>?</p>
<p>Well, you could do that, and could probably find a way to test for whether the difference in the slopes is different from 0. This would be a test of the null hypothesis that the effect of minutes of exercise on blood pressure is the same for people with different diets. But, this would be a more complicated way to do it, and would not be as general as the model with the interaction term. The model with the interaction term is more general, more flexible, and more elegant.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is usually better model the whole dataset to test a single hypothesis, rather dividing up the dataset into smaller parts, fitting a model to each part, and then comparing the results of the models. The latter approach is less efficient and less elegant. <strong>One hypothesis = one model.</strong></p>
</div>
</div>
</section>
<section id="ancova" class="level2">
<h2 class="anchored" data-anchor-id="ancova">ANCOVA</h2>
<p>The example we just worked through was with one continuous explanatory variable (minutes of exercise) and one categorical explanatory variable (diet). This is an example of an analysis of covariance (ANCOVA). ANCOVA is a type of linear model in which there are both continuous and categorical explanatory variables.</p>
<p>ANCOVA is often used in two main ways.</p>
<p>First, it can be used to account for covariates (continuous variables). In this case, the main interest is in comparing groups (as in ANOVA), while one or more continuous variables are included to explain additional variation in the response. These covariates are not the main focus of interpretation; instead, they help adjust group means and improve the precision of group comparisons.</p>
<p>Second, ANCOVA can be used to test whether covariate effects differ between groups. Here, the continuous variable is of real interest, and the question is whether the relationship between the covariate and the response is the same across groups. This is done by including a group × covariate interaction, which allows the slope of the relationship to differ between groups.</p>
<p>An important distinction is that the first use assumes the covariate has the same effect in all groups (parallel slopes), while the second explicitly tests whether this assumption is valid.</p>
</section>
<section id="two-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="two-way-anova">Two-way ANOVA</h2>
<p>Above we had an example with two categorical explanatory variables (diet [levels: meat heavy or vegetarian] and exercise [levels: low or high]) and one continuous response variable (blood pressure). This is an example of a two-way ANOVA. Two-way ANOVA is used to test for effects of two categorical explanatory variables, as well as their interaction effect on a continuous response variable.</p>
<p>Here are the first few rows of the data again:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        diet exercise reps        bp
1 meat heavy     high    1  83.73546
2 meat heavy      low    1 115.11781
3 vegetarian     high    1  74.18977
4 vegetarian      low    1 108.58680
5 meat heavy     high    2  91.83643
6 meat heavy      low    2 103.89843</code></pre>
</div>
</div>
<p>Here is the graph of the data again:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="528"></p>
</figure>
</div>
</div>
</div>
<p>We can fit a two-way ANOVA model in R as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mod_2cat <span class="ot">&lt;-</span> <span class="fu">lm</span>(bp <span class="sc">~</span> diet <span class="sc">*</span> exercise, <span class="at">data=</span>bp_2cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Recall that this fits a model with main effects of diet and exercise, as well as their interaction effect. Recall that we could specify the model equivalently as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mod_2cat <span class="ot">&lt;-</span> <span class="fu">lm</span>(bp <span class="sc">~</span> diet <span class="sc">+</span> exercise <span class="sc">+</span> diet<span class="sc">:</span>exercise, <span class="at">data=</span>bp_2cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can check the model assumptions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_2cat, <span class="at">add.smooth=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>These look ok.</p>
<p><em>Hypothesis testing</em> the interaction is just as before. We use an F-test on the interaction term to test the null hypothesis that there is no interaction between diet and exercise on blood pressure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_2cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bp
              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
diet           1 2879.8  2879.8  34.695 9.741e-07 ***
exercise       1 4776.5  4776.5  57.546 5.680e-09 ***
diet:exercise  1 1142.5  1142.5  13.765  0.000696 ***
Residuals     36 2988.1    83.0                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>In the ANOVA table we see four rows. The first row is for the main effect of diet, the second row is for the main effect of exercise, the third row is for the interaction effect between diet and exercise, and the fourth row is for the residuals. As always, an interaction term in the R output is shown with a colon <code>:</code> between the two variables (here it looks like <code>diet:exercise</code>).</p>
<p>In this example, the F-statistic for the interaction term is quite large (13.76 and the corresponding p-value is quite small (7^{-4}. Hence, we conclude that there is a strong evidence of an interaction between diet and exercise on blood pressure. The effect of exercise on blood pressure depends on diet.</p>
<!---
**Think-Pair-Share** (#tps-two-way-report) Write a sentence reporting the results of the two-way ANOVA. Focus on the biological interpretation of the results, rather than the statistical details. Include statistics in parentheses, in support of your statements.
--->
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Reporting two-way ANOVA results</strong> When reporting the results of a two-way ANOVA, it is important to focus on the biological interpretation of the results, rather than the statistical details. Include statistics in parentheses, in support of your statements. For example, you might say something like: “The effect of exercise was different for people on different diets, with a stronger effect for those on a vegetarian diet compared to those on a meat heavy diet (F(1, 36) = 13.77, p &lt; 0.001).”</p>
</div>
</div>
<section id="more-than-two-levels" class="level3">
<h3 class="anchored" data-anchor-id="more-than-two-levels">More than two levels</h3>
<p>What if we had a categorical explanatory variable with more than two levels? For example, what if diet had three levels: meat heavy, vegetarian, and vegan?</p>
<p>Here is an example dataset.</p>
<p>Read in the dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>bp_2cat_3levels <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/bp_3cat.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the first few rows of the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bp_2cat_3levels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        diet exercise reps        bp
1 meat heavy     high    1  83.73546
2 meat heavy      low    1 115.11781
3      vegan     high    1  59.18977
4      vegan      low    1  98.58680
5 vegetarian     high    1  68.35476
6 vegetarian      low    1  98.98106</code></pre>
</div>
</div>
<p>Here is the graph of the data:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="528"></p>
</figure>
</div>
</div>
</div>
<p>Or plotted differently:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>The hypothesis testing is the same as before. We fit the model with interaction term:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mod_2cat_3levels <span class="ot">&lt;-</span> <span class="fu">lm</span>(bp <span class="sc">~</span> diet <span class="sc">*</span> exercise, <span class="at">data=</span>bp_2cat_3levels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We check the model assumptions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_2cat_3levels, <span class="at">add.smooth=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>These look ok.</p>
<p>Now we do the ANOVA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_2cat_3levels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bp
              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
diet           2 8724.1  4362.1  55.636 7.644e-14 ***
exercise       1 9078.3  9078.3 115.789 4.791e-15 ***
diet:exercise  2 1741.3   870.6  11.104 9.130e-05 ***
Residuals     54 4233.8    78.4                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><em>Important</em>: Although we have a categorical variable with three rather than two levels, we still have only four rows in the ANOVA table. One for each main effect (diet and exercise), one for the interaction effect (diet:exercise), and one for the residuals. This is because the ANOVA table tests each effect as a whole, rather than testing each level of the categorical variable separately.</p>
<p>In this case, we see that there is strong evidence of main effects of diet and exercise on blood pressure, as well as strong evidence of an interaction effect between diet and exercise on blood pressure.</p>
<p>Reporting the patterns and statistics is similar to before, but now we have more levels to consider so the reporting is a bit more complex, and we have to be careful to not over-interpret the results. For example, when the hypothesis test is on the interaction term via an F-test, we can only say that there is evidence of an interaction between diet and exercise on blood pressure. We cannot say which diets have different effects of exercise on blood pressure. To do that, we would need to do post-hoc tests, such as pairwise comparisons between the levels of diet within each level of exercise.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Degrees of freedom</strong> Look at the ANOVA table and the degrees of freedom column. For diet, the degrees of freedom is 2, because there are three levels of diet (meat heavy, vegetarian, vegan), and the degrees of freedom is number of levels minus 1. For exercise, the degrees of freedom is 1, because there are two levels of exercise (low, high). For the interaction term diet:exercise, the degrees of freedom is 2, which is the product of the degrees of freedom for diet (2) and exercise (1).</p>
<p>Another way to think about this is how many parameters are estimated? The answer is as follows: six parameters are estimated in total, one for each of the combinations of diet and exercise (3 diets x 2 exercises = 6 combinations). Hence the residual degrees of freedom is total number of observations (60) minus 6.</p>
<p>Don’t worry if this is a bit confusing at first. It will become clearer with practice, and you can ask for it to be explained again and in different ways.</p>
</div>
</div>
</section>
</section>
<section id="multiple-regression-with-interaction-term" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-with-interaction-term">Multiple regression with interaction term</h2>
<p>Above we had the example of two continuous explanatory variables (age and minutes of exercise) and one continuous response variable (blood pressure). We saw evidence of an interaction between age and minutes of exercise on blood pressure.</p>
<p>Here are the first few rows of the data again:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         bp      age mins_per_week age_class mins_per_week_class
1  61.58319 35.93052     130.94479     30-40             120-140
2  83.86716 42.32743      70.63945     40-50               60-80
3  93.01438 54.37120      54.05203     50-60               40-60
4  82.14413 74.49247     198.53681     70-80             180-200
5  60.13102 32.10092     126.69865     30-40             120-140
6 102.00306 73.90338      42.64163     70-80               40-60</code></pre>
</div>
</div>
<p>Here is the data in a graph, with age represented by a colour gradient:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>We can fit a multiple regression model with an interaction term in R as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>mod_2cont <span class="ot">&lt;-</span> <span class="fu">lm</span>(bp <span class="sc">~</span> mins_per_week <span class="sc">*</span> age, <span class="at">data=</span>bp_2cont)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We check the model assumptions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod_2cont, <span class="at">add.smooth=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>These look ok.</p>
<p>Now we do the F-test for the interaction term:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod_2cont)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bp
                  Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
mins_per_week      1 14307.2 14307.2 1534142 &lt; 2.2e-16 ***
age                1 10220.0 10220.0 1095879 &lt; 2.2e-16 ***
mins_per_week:age  1  1764.8  1764.8  189242 &lt; 2.2e-16 ***
Residuals         96     0.9     0.0                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>It looks the same as in the two-way ANOVA case!</strong> This is because we still have two variables and their interaction, so the ANOVA table has one row for each main effect (mins_per_week and age), one row for the interaction effect (mins_per_week:age), and one row for the residuals.</p>
<p>The F-statistic for the interaction term is very large (1.8924178^{5}) and the corresponding p-value is very small (5.6^{-160}). Hence, we conclude that there is very strong evidence of an interaction between minutes of exercise and age on blood pressure. The effect of minutes of exercise on blood pressure depends on age, with a stronger effect for younger people compared to older people.</p>
</section>
<section id="intepreting-main-effects-and-interaction-effects" class="level2">
<h2 class="anchored" data-anchor-id="intepreting-main-effects-and-interaction-effects">Intepreting main effects and interaction effects</h2>
<p>The term <em>main effect</em> refers to the individual effect of each categorical explanatory variable on the response variable, ignoring the other variable. For example, the main effect of diet would be the difference in blood pressure between meat heavy and vegetarian diets, averaged over both levels of exercise.</p>
<p>However, if there is an interaction between the two categorical explanatory variables, the main effects may not fully capture the relationship. The interaction effect indicates that the effect of one categorical variable on the response variable depends on the level of the other categorical variable. For example, the effect of diet on blood pressure may differ between low and high exercise groups.</p>
<p>We can see this in the example:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>There is a main effect of diet on blood pressure, as well as a main effect of exercise on blood pressure. However, there is also an interaction effect between diet and exercise on blood pressure, as the effect of diet on blood pressure depends on the level of exercise.</p>
<p>It could look otherwise. For example, if we found a (albeit rather unlikely pattern) of higher blood pressure for vegetarians how exercise little, and lower blood pressure for vegetarians who exercise a lot, we would have a pattern as follows:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Here there is no main effect of diet on blood pressure, as the average blood pressure for meat heavy and vegetarian diets is the same when averaged over both levels of exercise. There is still a main effect of exercise on blood pressure, as blood pressure is lower for high exercise compared to low exercise. And there is still an interaction effect between diet and exercise on blood pressure, as the effect of diet on blood pressure depends on the level of exercise.</p>
<p><strong>Take home</strong>: Interactions are very interesting, but also will require careful and nuanced interpretation.</p>
</section>
<section id="more-than-two-explanatory-variables" class="level2">
<h2 class="anchored" data-anchor-id="more-than-two-explanatory-variables">More than two explanatory variables</h2>
<p>All the examples above had two explanatory variables. What if we have more than two explanatory variables? The principles are the same, but the models and interpretations become more complex. For example, if we have three categorical explanatory variables (A, B, C), we can fit a model with main effects of A, B, and C, as well as all possible interaction effects (A:B, A:C, B:C, A:B:C). The ANOVA table will have one row for each main effect, one row for each two-way interaction effect, one row for the three-way interaction effect, and one row for the residuals.</p>
<p>Interpretation of three-way interactions can be quite complex, as it involves understanding how the effect of one variable on the response variable depends on the levels of the other two categorical variables. Very careful consideration and visualization of the data are often necessary to fully understand and communicate the results.</p>
</section>
<section id="review" class="level2">
<h2 class="anchored" data-anchor-id="review">Review</h2>
<ul>
<li>Interactions are some of the most interesting effects in biology and medicine. They occur when the effect of one explanatory variable on the response variable depends on the level of another explanatory variable.</li>
<li>Interactions can occur between continuous and categorical explanatory variables, or between two categorical explanatory variables, or between two continuous explanatory variables.</li>
<li>Visualization is key to understanding interactions. Use graphs to explore and communicate interactions.</li>
<li>Hypothesis testing for interactions is done using <span class="math inline">\(F\)</span>-tests on the interaction terms in linear models.</li>
<li>The degrees of freedom for interaction terms depend on the levels of the categorical variables involved. Each categorical variable takes degrees of freedom equal to the number of levels minus one. Each continuous variable takes one degree of freedom. The degrees of freedom for the interaction term is the product of the degrees of freedom of the individual variables.</li>
<li>Report interactions carefully, focusing on the biological interpretation and including relevant statistics (i.e., the <span class="math inline">\(F\)</span>-statistic, degrees of freedom for the interaction term, degrees of freedom for error, and p-value).</li>
</ul>
</section>
<section id="further-reading" class="level2">
<h2 class="anchored" data-anchor-id="further-reading">Further reading</h2>
<ul>
<li>Wikipedia is always a good place to start for understanding concepts: <a href="https://en.wikipedia.org/wiki/Interaction_(statistics)">Interaction term (statistics)</a></li>
<li>This is a nice paper for clinicians on understanding interactions: <a href="https://publications.aap.org/hospitalpediatrics/article/13/10/e319/194006/How-to-Interact-With-Interactions-What-Clinicians?autologincheck=redirected">How to interact with interactions: what clinicians should know about statistical interactions</a></li>
<li>If you want a challenge, and to see how nuanced interactions and interpretation can be, have a look at this paper <a href="https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13714">Interactions in statistical models: Three things to know</a></li>
</ul>
</section>
<section id="extras" class="level2">
<h2 class="anchored" data-anchor-id="extras">Extras</h2>
<section id="degrees-of-freedom" class="level3">
<h3 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of freedom</h3>
<p>It can be useful to think about degrees of freedom in terms of how many parameters / coefficients have to be estimated by the model.</p>
<p>In one-way ANOVA, this is the number of groups one has. So if you have a categorical variable with five categories (in another language one would say a factor variable with five levels), there will be five means estimated, and so the model uses five degrees of freedom. So error degrees of freedom will be the total number of observation minus five.</p>
<p>In two-way ANOVA (which includes the interaction of the two categorical variables) we have to estimate a mean for each of the combinations of the categories. So if we have one categorical variable with three levels and another with four, there are 3*4 combinations, so 12 means to estimate. So the model takes 12 degrees of freedom, and the error degrees of freedom will be the number of observations minus 12.</p>
<p>If we made a two-way ANOVA without an interaction (i.e.&nbsp;we included only the main effects) between the two explanatory variables, and we could have (i.e.&nbsp;we had performed a fully factorial experiment), well, this is just weird. Why would we not do the analysis we planned when we designed the experiment?</p>
<p>(I raised that in case anyone wants to know how to calculate degrees of freedom with only main effects. In that case, the two explanatory variables share the same reference level (intercept) so in the case above, only 6 things would need to be estimated: A shared intercept, and the other five means. Its a bit like when we previously made a regression model with two regression lines, both with the same slope. They shared the same slope – so only one needed to be estimated. So often when we use only main effects, getting the degrees of freedom is a bit tricky.)</p>
<p>Bottom line: more explanatory variables, more interactions, more levels in categorical explanatory variables = more things have to be estimated = fewer degrees of freedom for error. And few degrees of freedom for error is not good, generally speaking.</p>
</section>
<section id="d-scatter-plot" class="level3">
<h3 class="anchored" data-anchor-id="d-scatter-plot">3d scatter plot</h3>
<p>Here is a 3D scatter plot of the data with two continuous explanatory variables (age and minutes of exercise) and one continuous response variable (blood pressure). This plot helps to visualise the interaction between age and minutes of exercise on blood pressure.</p>
<p>(Please note that this plot is best viewed in the HTML version of the book; in the PDF version, it will appear as a static image.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>plotly<span class="sc">::</span><span class="fu">plot_ly</span>(bp_2cont, <span class="at">x =</span> <span class="sc">~</span>mins_per_week, <span class="at">y =</span> <span class="sc">~</span>age, <span class="at">z =</span> <span class="sc">~</span>bp, <span class="at">type =</span> <span class="st">"scatter3d"</span>, <span class="at">mode =</span> <span class="st">"markers"</span>, <span class="at">color =</span> age, <span class="at">width=</span><span class="dv">500</span>, <span class="at">height=</span><span class="dv">500</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  plotly<span class="sc">::</span><span class="fu">layout</span>(<span class="at">title =</span> <span class="st">"3D Scatter plot of Blood Pressure vs Exercise and Age"</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">scene =</span> <span class="fu">list</span>(<span class="at">xaxis =</span> <span class="fu">list</span>(<span class="at">title =</span> <span class="st">"Minutes per week of exercise"</span>),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">yaxis =</span> <span class="fu">list</span>(<span class="at">title =</span> <span class="st">"Age"</span>),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">zaxis =</span> <span class="fu">list</span>(<span class="at">title =</span> <span class="st">"Blood Pressure"</span>))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="htmlwidget-7bf94cd961c11210a1ca" style="width:100%;height:650px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-7bf94cd961c11210a1ca">{"x":{"visdat":{"d8906fc6c36f":["function () ","plotlyVisDat"]},"cur_data":"d8906fc6c36f","attrs":{"d8906fc6c36f":{"x":{},"y":{},"z":{},"mode":"markers","color":[35.930519788525999,42.327433978207409,54.371201801113784,74.492467399686575,32.100915862247348,73.9033810980618,76.680516116321087,59.647867549210787,57.746842633932829,23.707176228053868,32.358474493958056,30.593405151739717,61.221370799466968,43.046223092824221,66.190485199913383,49.861954525113106,63.057110495865345,79.514365689828992,42.80211076606065,66.646713279187679,76.082313866354525,32.728551276959479,59.100425965152681,27.533305757679045,36.033240123651922,43.166845552623272,20.803419989533722,42.943277424201369,72.181450743228197,40.420939801260829,48.924806928262115,55.973949525505304,49.612478422932327,31.173056084662676,69.642399116419256,60.108004291541874,67.654391643591225,26.476617553271353,63.422656762413681,44.6764657786116,69.256777646951377,58.823611629195511,66.975965737365186,53.182178698480129,51.783174811862409,67.361373901367188,21.399872140027583,48.633803902193904,63.938824320212007,61.563893388956785,48.657177328132093,71.672568609938025,46.285826433449984,34.687836621887982,24.240742828696966,25.967969610355794,38.976302430965006,51.118055791594088,59.720304585061967,44.409811231307685,74.772555455565453,37.616202365607023,47.543943575583398,39.943680451251566,59.052228024229407,35.481006843037903,48.712714896537364,65.978640238754451,25.054814862087369,72.51927980221808,40.344376270659268,70.366421011276543,40.801009349524975,40.026495847851038,48.581074704416096,73.531900150701404,71.860368237830698,43.399372608400881,66.639241930097342,77.637079833075404,46.079569086432457,62.750880722887814,43.999662133865058,39.521129112690687,65.425228881649673,32.16153530869633,62.667273348197341,27.301515261642635,34.729310837574303,28.598262765444815,34.377764905802906,23.53606263641268,58.53729551192373,72.576152761466801,66.734880646690726,67.83852955326438,47.316467217169702,44.605044922791421,68.652214566245675,56.295997416600585],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d"}},"layout":{"width":500,"height":500,"margin":{"b":40,"l":60,"t":25,"r":10},"title":"3D Scatter plot of Blood Pressure vs Exercise and Age","scene":{"xaxis":{"title":"Minutes per week of exercise"},"yaxis":{"title":"Age"},"zaxis":{"title":"Blood Pressure"}},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[130.94478561542928,70.639454387128353,54.052029177546501,198.53681223466992,126.69865288771688,42.641627043485641,25.874469615519047,95.623606862500324,184.81489396654069,119.75219342857601,195.23413898423317,146.35850237682462,71.345382416620851,86.294738110154867,29.6423121355474,2.6155150961130857,143.11321321874857,20.636847149580721,89.256869722157717,128.02020902745426,198.3677240088582,99.118715571239605,96.869904873892665,34.688466973602772,150.96418890170753,90.779097843915224,102.2339567542076,41.509022656828165,45.731628546491272,119.1423992626369,114.97443965636194,15.41287605650723,7.1081159170717001,128.55909843929112,185.72303992696104,119.61848447099328,112.18014960177244,105.20554478280246,197.01904477551579,101.52836446650326,136.55761573463678,120.30824352987111,47.773735551163554,51.633185334503651,145.8619246724993,90.514166280627236,35.025353683158755,149.33965392410755,20.997528079897165,172.9089898057282,122.92899433523417,111.43190776929259,65.755463810637593,90.62628909014164,100.08819452486932,36.173272226005793,105.92612056061624,15.055149141699076,55.551186529919512,42.539903847500682,56.958096195012331,179.01882058940828,89.247064664959908,155.99697795696557,176.12380697391927,82.624841900542378,12.761696102097631,67.097498336806893,144.74518932402134,67.523066699504852,126.08282449655236,168.12291080132127,171.22633294202387,78.271856205537915,76.098777120932937,179.08908519893885,128.86315258219838,148.21572974324226,121.06068930588664,180.61632229946557,58.746031019836657,38.252021977677941,177.29018866084516,100.66789714619516,175.41150860488415,37.838724488392472,151.62061047740281,144.89977853372693,188.7449636589736,109.5293174032122,142.34877354465425,77.781019965186715,20.174625236541036,185.46041771769524,56.646500062197447,118.1146317627281,22.072120988741521,168.10140642337501,63.592736888676882,156.57026739791036],"y":[35.930519788525999,42.327433978207409,54.371201801113777,74.492467399686575,32.100915862247348,73.9033810980618,76.680516116321087,59.647867549210787,57.746842633932829,23.707176228053868,32.358474493958056,30.59340515173972,61.221370799466968,43.046223092824221,66.190485199913383,49.861954525113113,63.057110495865352,79.514365689828992,42.80211076606065,66.646713279187679,76.082313866354525,32.728551276959479,59.100425965152681,27.533305757679045,36.033240123651922,43.166845552623272,20.803419989533719,42.943277424201369,72.181450743228197,40.420939801260829,48.924806928262122,55.973949525505297,49.612478422932327,31.173056084662679,69.642399116419256,60.108004291541874,67.654391643591225,26.476617553271357,63.422656762413681,44.6764657786116,69.256777646951377,58.823611629195511,66.975965737365186,53.182178698480129,51.783174811862409,67.361373901367188,21.399872140027583,48.633803902193904,63.938824320212007,61.563893388956792,48.657177328132093,71.672568609938025,46.285826433449984,34.687836621887982,24.24074282869697,25.967969610355794,38.976302430965006,51.118055791594088,59.720304585061967,44.409811231307685,74.772555455565453,37.616202365607023,47.543943575583398,39.943680451251566,59.052228024229407,35.481006843037903,48.712714896537364,65.978640238754451,25.054814862087369,72.51927980221808,40.344376270659268,70.366421011276543,40.801009349524975,40.026495847851038,48.581074704416096,73.531900150701404,71.860368237830698,43.399372608400881,66.639241930097342,77.637079833075404,46.079569086432457,62.750880722887807,43.999662133865058,39.521129112690687,65.425228881649673,32.16153530869633,62.667273348197341,27.301515261642635,34.729310837574303,28.598262765444812,34.377764905802906,23.53606263641268,58.53729551192373,72.576152761466801,66.734880646690726,67.83852955326438,47.316467217169702,44.605044922791421,68.652214566245675,56.295997416600585],"z":[61.58319355721293,83.86716200070984,93.014382357343237,82.14412856501832,60.131020659017821,102.00305538518133,104.72282597324464,86.762721930181556,66.768038807369621,56.857770283105559,37.142598845240187,52.221949656805883,92.43198465427902,79.665496361006774,101.58734949135324,104.29123058542126,79.838633650122219,105.80973071857922,78.80310717105219,85.297464590936769,83.835150830976616,70.067861049991578,86.078895424968621,90.166582273208959,55.309854831227952,78.591638744183683,61.590086879184973,92.448720374657526,100.78904121988246,68.51770606344715,75.536788218051854,102.14566520781996,103.22359574083774,58.723816909850491,78.804366092780825,81.998055100954787,88.592665629764085,63.919496241970521,70.244890072696123,76.37741717005548,85.743136099466582,81.230724695144914,98.642691931636918,93.185098608605514,69.901730852986006,91.889765340703022,88.583717479380425,66.51007020896769,102.47927463432548,72.762586954550045,73.353128656015571,91.382502267730601,86.936773825522693,73.780852450406726,64.362291907750659,89.099373787731352,71.677615394706962,101.3700541077109,94.645663406949922,92.803903759950202,100.33522951771258,47.898386144482657,81.45249736353577,57.239988526149702,69.783911060236434,77.114352884876993,101.57320505467948,95.041673908873761,48.251266467458343,97.994769299818756,66.657487782477702,82.136804552691714,53.443670400744864,80.523746825553275,85.260120706872243,83.648978467413727,89.13399247746959,62.601945297849262,86.57328159833942,87.688956841013862,88.646768031230451,99.249206983107925,54.780406366961898,73.363984138351498,76.270561354737737,90.365673194549117,78.111132037355091,49.983571634576244,41.832340638573584,63.664297623284988,56.713842679847005,72.656592248120035,101.59808211217847,81.910461771521696,97.130916858457439,87.68535332022546,99.061575943916594,57.799070459556482,96.938961572199119,71.377755282340104],"mode":"markers","type":"scatter3d","marker":{"colorbar":{"title":"","ticklen":2},"cmin":20.803419989533722,"cmax":79.514365689828992,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":false,"color":[35.930519788525999,42.327433978207409,54.371201801113784,74.492467399686575,32.100915862247348,73.9033810980618,76.680516116321087,59.647867549210787,57.746842633932829,23.707176228053868,32.358474493958056,30.593405151739717,61.221370799466968,43.046223092824221,66.190485199913383,49.861954525113106,63.057110495865345,79.514365689828992,42.80211076606065,66.646713279187679,76.082313866354525,32.728551276959479,59.100425965152681,27.533305757679045,36.033240123651922,43.166845552623272,20.803419989533722,42.943277424201369,72.181450743228197,40.420939801260829,48.924806928262115,55.973949525505304,49.612478422932327,31.173056084662676,69.642399116419256,60.108004291541874,67.654391643591225,26.476617553271353,63.422656762413681,44.6764657786116,69.256777646951377,58.823611629195511,66.975965737365186,53.182178698480129,51.783174811862409,67.361373901367188,21.399872140027583,48.633803902193904,63.938824320212007,61.563893388956785,48.657177328132093,71.672568609938025,46.285826433449984,34.687836621887982,24.240742828696966,25.967969610355794,38.976302430965006,51.118055791594088,59.720304585061967,44.409811231307685,74.772555455565453,37.616202365607023,47.543943575583398,39.943680451251566,59.052228024229407,35.481006843037903,48.712714896537364,65.978640238754451,25.054814862087369,72.51927980221808,40.344376270659268,70.366421011276543,40.801009349524975,40.026495847851038,48.581074704416096,73.531900150701404,71.860368237830698,43.399372608400881,66.639241930097342,77.637079833075404,46.079569086432457,62.750880722887814,43.999662133865058,39.521129112690687,65.425228881649673,32.16153530869633,62.667273348197341,27.301515261642635,34.729310837574303,28.598262765444815,34.377764905802906,23.53606263641268,58.53729551192373,72.576152761466801,66.734880646690726,67.83852955326438,47.316467217169702,44.605044922791421,68.652214566245675,56.295997416600585],"line":{"colorbar":{"title":"","ticklen":2},"cmin":20.803419989533722,"cmax":79.514365689828992,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":false,"color":[35.930519788525999,42.327433978207409,54.371201801113784,74.492467399686575,32.100915862247348,73.9033810980618,76.680516116321087,59.647867549210787,57.746842633932829,23.707176228053868,32.358474493958056,30.593405151739717,61.221370799466968,43.046223092824221,66.190485199913383,49.861954525113106,63.057110495865345,79.514365689828992,42.80211076606065,66.646713279187679,76.082313866354525,32.728551276959479,59.100425965152681,27.533305757679045,36.033240123651922,43.166845552623272,20.803419989533722,42.943277424201369,72.181450743228197,40.420939801260829,48.924806928262115,55.973949525505304,49.612478422932327,31.173056084662676,69.642399116419256,60.108004291541874,67.654391643591225,26.476617553271353,63.422656762413681,44.6764657786116,69.256777646951377,58.823611629195511,66.975965737365186,53.182178698480129,51.783174811862409,67.361373901367188,21.399872140027583,48.633803902193904,63.938824320212007,61.563893388956785,48.657177328132093,71.672568609938025,46.285826433449984,34.687836621887982,24.240742828696966,25.967969610355794,38.976302430965006,51.118055791594088,59.720304585061967,44.409811231307685,74.772555455565453,37.616202365607023,47.543943575583398,39.943680451251566,59.052228024229407,35.481006843037903,48.712714896537364,65.978640238754451,25.054814862087369,72.51927980221808,40.344376270659268,70.366421011276543,40.801009349524975,40.026495847851038,48.581074704416096,73.531900150701404,71.860368237830698,43.399372608400881,66.639241930097342,77.637079833075404,46.079569086432457,62.750880722887814,43.999662133865058,39.521129112690687,65.425228881649673,32.16153530869633,62.667273348197341,27.301515261642635,34.729310837574303,28.598262765444815,34.377764905802906,23.53606263641268,58.53729551192373,72.576152761466801,66.734880646690726,67.83852955326438,47.316467217169702,44.605044922791421,68.652214566245675,56.295997416600585]}},"frame":null},{"x":[2.6155150961130857,198.53681223466992],"y":[20.803419989533719,79.514365689828992],"type":"scatter3d","mode":"markers","opacity":0,"hoverinfo":"none","showlegend":false,"marker":{"colorbar":{"title":"","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"cmin":20.803419989533722,"cmax":79.514365689828992,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":true,"color":[20.803419989533722,79.514365689828992],"line":{"color":"rgba(255,127,14,1)"}},"z":[37.142598845240187,105.80973071857922],"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="types-of-sums-of-squares" class="level3">
<h3 class="anchored" data-anchor-id="types-of-sums-of-squares">Types of sums of squares</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>A note on anova() and “Type I” (sequential) sums of squares</strong></p>
<p>In this course we often use <code>anova()</code> to test terms in a linear model. In base R, <code>anova()</code> for an <code>lm</code> uses Type I (sequential) sums of squares. That means the test for each term is done in the order the terms appear in the model formula: each term is tested after the terms before it have already been included.</p>
<p>In balanced designs (equal sample sizes in each group/combination), the order usually does not matter much. But in unbalanced designs (unequal sample sizes), the p-value for a ““main effect” or an interaction can change if you change the order of terms in the model formula.</p>
<p>This is related to collinearity between explanatory variables. When explanatory variables are correlated, the variance they explain in the response variable overlaps. In that case, the order of terms matters because earlier terms get to “claim” more of the shared variance.</p>
<p>So: when you see an ANOVA table from <code>anova()</code>, remember that it is testing terms sequentially, not “all at once”.</p>
</div>
</div>
</section>
<section id="box-and-whisker-plot-for-two-cats" class="level3">
<h3 class="anchored" data-anchor-id="box-and-whisker-plot-for-two-cats">Box and whisker plot for two cats</h3>
<p>Often you will see box and whisker plots used to visualise data with two categorical explanatory variables. Here is how to make such a plot in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bp_2cat, <span class="fu">aes</span>(<span class="at">x=</span>diet, <span class="at">y=</span>bp, <span class="at">fill=</span>exercise)) <span class="sc">+</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.8</span>)) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Blood pressure vs diet and exercise"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Diet"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Blood pressure"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill=</span><span class="st">"Exercise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>I (Owen) prefer to show the individual data points whenever possible, so here is a box and whisker plot with the individual data points overlaid:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bp_2cat, <span class="fu">aes</span>(<span class="at">x=</span>diet, <span class="at">y=</span>bp, <span class="at">fill=</span>exercise)) <span class="sc">+</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.8</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">col=</span>exercise), <span class="at">position=</span><span class="fu">position_jitterdodge</span>(<span class="at">jitter.width=</span><span class="fl">0.2</span>, <span class="at">dodge.width=</span><span class="fl">0.8</span>), <span class="at">size=</span><span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Blood pressure vs diet and exercise"</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Diet"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Blood pressure"</span>,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill=</span><span class="st">"Exercise"</span>,</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"Exercise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>I, and others, prefer to not use bar plots with error bars to visualise data with categorical explanatory variables. Bar plots hide the individual data points and can be misleading. Box and whisker plots are better, but still hide some of the data. Scatter plots with jittered points are often the best way to visualise such data.</p>
<p>In case you must use bar plots with error bars, here is how to make one in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>grouped_data <span class="ot">&lt;-</span> <span class="fu">group_by</span>(bp_2cat, diet, exercise) <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_bp =</span> <span class="fu">mean</span>(bp), <span class="at">sd_bp =</span> <span class="fu">sd</span>(bp), <span class="at">n =</span> <span class="fu">n</span>(), <span class="at">se_bp =</span> sd_bp <span class="sc">/</span> <span class="fu">sqrt</span>(n), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(grouped_data, <span class="fu">aes</span>(<span class="at">x=</span>diet, <span class="at">y=</span>mean_bp, <span class="at">fill=</span>exercise)) <span class="sc">+</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"identity"</span>, <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.8</span>), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>mean_bp <span class="sc">-</span> se_bp, <span class="at">ymax=</span>mean_bp <span class="sc">+</span> se_bp), <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.8</span>), <span class="at">width=</span><span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Blood pressure vs diet and exercise"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Diet"</span>,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Blood pressure"</span>,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill=</span><span class="st">"Exercise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="7.1-interactions_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/opetchey\.github\.io\/BIO144_Course_Book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./6.1-multiple-regression.html" class="pagination-link" aria-label="Multiple regression (L6)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Multiple regression (L6)</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./8.1-GLM1-count-data.html" class="pagination-link" aria-label="Count data (L8)">
        <span class="nav-page-text">Count data (L8)</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>BIO144 Data Analysis for Biologists, Course Book written by Owen Petchey</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/opetchey/BIO144_Course_Book/edit/main/7.1-interactions.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/opetchey/BIO144_Course_Book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>